### ISSUE TITLE
Update-ApplicationFlightSubmission sends "UpdatePublishMode" switch to Patch-ApplicationFlightSubmission but it expects "UpdatePublishModeAndVisibility"

### ISSUE THREAD

**Issue by EdmundoMartinez** [Microsoft/StoreBroker#143]
```
Update-ApplicationFlightSubmission uses switch “UpdatePublishMode” (StoreIngestionFlightingApi.ps1@1271).
In this function, Patch-ApplicationFlightSubmission is called sending “UpdatePublishMode” parameter (StoreIngestionFlightingApi.ps1@1368)
Patch-ApplicationFlightSubmission expects “UpdatePublishModeAndVisibility” (StoreIngestionFlightingApi.ps1@1586)
```

If Update-ApplicationFlightSubmission is called with -UpdatePublishMode as documented, this value will not be correctly propagated to Patch-ApplicationFlightSubmission.

**Comment by HowardWolosky** [comment]
Thanks for the report.  This is indeed a real bug/typo, but it has no actual impact to end-users.

As long as there is an unambiguous parameter that it can match, PowerShell does best-effort parameter matching.  This wasn’t the intention (it should have been a named parameter of $UpdatePublishMode, as we try to use explicit parameter notation throughout the code), but passing in -UpdatePublishMode is sufficiently unambiguous such that PowerShell will cause that to be a switch match.

You can see this for yourself. Just enter this into a PowerShell console window:

```powershell
function Test-Param([switch]$UpdatePublishModeAndVisibility)
{
    if ($UpdatePublishModeAndVisibility)
    {
       Write-Host "switch provided"
    }
    else
    {
         write-host "switch not provided"
    }
 }

Test-Param -UpdatePublishMode
```

Even though you didn’t provide the whole switch name, it still matched what was provided since it was unambiguous.

Given that this isn't having _any_ end-user impact, and the code doesn't exist at all in the `v2` branch, it's pretty low-priority to fix this.
