### ISSUE TITLE
Rate-limiting on Commit-InAppProductSubmission

### ISSUE THREAD

**Issue by adamhewitt627** [microsoft/StoreBroker#159]
I'm being heavily rate-limited on _just_ the `Commit` endpoint, despite having only one process running to do commits. On average, I get about 1 submission through every 3-4 minutes. It _does_ happen with the REST API directly, so it isn't exactly a StoreBroker issue, but wondered if you have seen similar behavior and might have some insight.

Also, there was previous mention of a V2 to the Store API. Is that something that's available yet? I don't see reference to it.

**Comment by HowardWolosky** [comment]
>... but wondered if you have seen similar behavior and might have some insight.

I've seen limited usage of the IAP support (and I haven't directly worked with anyone that _does_ use it), so I haven't experienced that specific rate limiting.  It does seem odd that the rate limiting that you're experiencing is _specifically_ on the the `Commit` endpoint.  There are _two_ rate limits that the API poses that I'm aware of: per _minute_ and a per _day_.  It sounds like you're hitting that per _minute_ limit, and it's possible that they have a different limit on IAP's vs App's.  I'll reach out the API team to see if they have any idea on what might be going on.  If you're willing to share out your `AppId`, that might help them investigate the issue a bit further.

>Also, there was previous mention of a V2 to the Store API. Is that something that's available yet? I don't see reference to it.

The v2 API is not yet available and I cannot comment on when it will be.  You can see follow the ongoing development of StoreBroker v2 against those unreleased API's in the [v2 branch](https://github.com/microsoft/StoreBroker/tree/v2).

Since there isn't anything in this issue that is specific to StoreBroker, I'm going to close it out.  That being said, I will update it with a response from the API team (if I get one) regarding the rate limiting that you're experiencing.

**Comment by adamhewitt627** [comment]
Certainly, the AppId is `9NRSP6BRXBZQ`. I did also think it odd that it was only on that API. We have ~20,000 IAPs and so I've written .NET command line utilities instead of StoreBroker to parallelize most of the API usage, using the `Retry-After` header (instead of an increasing delay) to maximize my throughput. As a result, I do get `429` back from create/update/delete, but the limit is more like 60/minute. Commit will give `429` on the first call, without any other API calls being made.

One more thought: based on my logging there are times where `Commit` will succeed on 2-3 submissions in parallel. It's almost like the Commit API internally calls to a rate-limited endpoint and then propagates that error to me.

Thank you for the help and I hope the API team can have an answer.

**Comment by HowardWolosky** [comment]
> using the `Retry-After` header (instead of an increasing delay) to maximize my throughput

I didn't realize that they added that to v1 (that header didn't exist when I initially wrote the retry support).  v2 _does_ [use the `Retry-After` header](https://github.com/microsoft/StoreBroker/blob/v2/StoreBroker/StoreIngestionApi.psm1#L2103).

Thanks for the `AppId`.  I'll include that in my message to them for context.
