### ISSUE TITLE
We need a feature that allows us to download symbols for the appcenter.ms

### ISSUE THREAD

**Issue by Paradoxon101** [microsoft/StoreBroker#182]
With version 2.5 of the App Center SDK, symbols must be uploaded. These must first be downloaded from the Windows Store.

For this we need an interface.

https://docs.microsoft.com/en-us/appcenter/diagnostics/windows-support#symbolication

**Comment by HowardWolosky** [comment]
It's possible that I'm misunderstanding here, so if I am, please forgive me and help clarify the issue.

This seems a bit similar to how you need to do your _first_ submission through the Store due to the requirement for completing some wizards to determine your app's age rating.  It sounds like the need to download the symbols is a one-time scenario, and the API team seems to leave one-time scenarios as non-API scenarios, leaving the API to focus on the repetitive tasks that developers are likely to encounter.

Future symbols can be uploaded as part of an [.appxupload file](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#types-of-app-packages).  I'll pass this feedback along to the API team, but I don't believe that they will be adding any additional API's to the v1 API.

**Comment by Paradoxon101** [comment]
Sorry, but it is not a one-time scenario. For each new app version, the recompiled symbols must be downloaded again from the Windows Store.

Important, this is a download not an upload!

This is also explained very well in the documentation from above:
"When you publish your application to the store, the .NET Native compilation happens on server side. Thus you need to download the symbols from the Partner Center."

**Comment by HowardWolosky** [comment]
As far as I can tell, there already exists the ability to do this in an automated fashion through the [_AppCenter_ REST API](https://openapi.appcenter.ms/#/build/builds_getDownloadUri) (which is different than the Submission API which StoreBroker interfaces with).

The [AppCenter CLI](https://github.com/microsoft/appcenter-cli) project has a command that will "Download the binary, logs, or **symbols** for a completed build" using that API I just referenced.

Have you given that a shot to see if it satisfies your needs?

**Comment by Paradoxon101** [comment]
Why should I have to download something from the Appcenter when the documentation tells me to upload it?
These are two different systems!

The required app symbols are ONLY here to download:
https://partner.microsoft.com/en-us/dashboard/apps/9NBLGGH68DCJ/managepackages

For this area, we need a REST access e.g. with the StoreBroker!

After downloading the symbols from partner.microsoft.com, we can upload them using App Center API:
curl -X PUT '{upload_url}' \
    -H 'x-ms-blob-type: BlockBlob' \
    --upload-file '{path to file}'

We use our internal build process. Therefore we need an API for the download. For the upload there is the App Center API.

**Comment by HowardWolosky** [comment]
Ok, I think I have a better understanding of the problem now.

From what I'm now understanding from this thread: there's a need to _download_ the symbols from _Partner Center_ and then to _upload_ the symbols to App Center.  The API (and CLI) exists already to both download/upload the symbols to _App Center_, however the API is missing for downloading the symbols from _Partner Center_.

Given this understanding, I have reached out to the Submission API team to get their take on the matter and will report back when I have more information to share.

**Comment by Paradoxon101** [comment]
That's exactly what I meant :)
