### ISSUE TITLE
Can't update the Flight Packages and the Notes For Certification for a new Flight

### ISSUE THREAD

**Issue by cosminstirbu** [microsoft/StoreBroker#183]
Hello,

I've been trying to create a new flight with a new package and notes for certification but I can't seem to make it work.

These are the steps that I'm taking:

`New-ApplicationFlight -AppId ... -FriendlyName "..." -GroupIds ...`
`Update-ApplicationFlightSubmission -AppId ... -Flight ... -SubmissionId ... -SubmissionDataPath "C:\Users\cosminst\Desktop\SBConfig.json" -UpdateNotesForCertification -PackagePath C:\Users\cosminst\Documents\....appxupload`

Using the following [SBConfig.json](https://gist.github.com/cosminstirbu/b9604c1223303fb8ea529b5e9c792713)

However, when I call

`Get-ApplicationFlightSubmission -AppId ... -FlightId ... -SubmissionId ... | Format-ApplicationFlightSubmission`

The Notes For Certification are empty, so is Flight Packages and Publish Mode is not reflected. 

```
Submission Id                       : 1152921505689281149
Flight Id                           : 46ed9740-4d9b-4258-9fba-3f4e096051aa
Publish Mode                        : Immediate
Publish Date                        : Mon, 01 Jan 1601 02:00:00 GMT
Notes For Certification             :

File Upload Url                     : https://ingestionpackagesprod1.blob.core.windows.net/ingestion/bc99e295-e92c-4b2a-95b5-fec955472961?sv=2017-04-17&sr=b&sig=NP43c9B%2B80DQwctovWvGNV4p2A2o9S0R%2BjQAgc3%2B6nE%3D&se=2019-12-14T09:34:31Z&sp=rwl

Flight Packages                     : <None>

Is Mandatory Update?                : False
Mandatory Update Effective Date     : Mon, 01 Jan 1601 02:00:00 GMT

Is Package Rollout?                 : False
Package Rollout Percentage          : 0.0%
Package Rollout Status              : PackageRolloutNotStarted
Fallback SubmissionId               : 0

Status                                 : PendingCommit
Status Details [Errors]                : <None>

Status Details [Warnings]              : <None>

Status Details [Certification Reports] : <None>
```

I'm not clear what I'm missing, not sure if the issue is with SBConfig.json. I've generated it using 

`New-StoreBrokerConfigFile -Path (Join-Path -Path ([System.Environment]::GetFolderPath('Desktop')) -ChildPath 'SBConfig.json') -AppId ...` and stripped out un needed properties as per:

> A Flight Submission is similar to an application submission, but it has much less metadata. The only data currently associated with it is its set of packages and its publish mode and date.

from https://github.com/microsoft/StoreBroker/blob/master/Documentation/USAGE.md#flighting

Thanks,
Cosmin

**Comment by cosminstirbu** [comment]
This is the output of `Update-ApplicationFlightSubmission` command

```
WARNING: 2019-12-13 11:20:30 : cosminst : The config file used to generate this submission did not have an AppId defined in it.
The AppId entry in the config helps ensure that payloads are not submitted to the wrong application.
Please update your app's StoreBroker config file by adding an "appId" property with
your app's AppId to the "appSubmission" section.  If you're unclear on what change
needs to be done, you can re-generate your config file using
   New-PackageToolConfigFile -AppId 9NP77JJ47ZWT -Path "C:\Users\cosminst\Desktop\newconfig.json"
and then diff the new config file against your current one to see the requested appId change.
DONE - Operation took 4 second(s) [Getting SubmissionId: 1152921505689281149 for AppId: 9NP77JJ47ZWT FlightId: 46ed9740-4d9b-4258-9fba-3f4e096051aa]
DONE - Operation took 7 second(s) [Replacing the content of Submission: 1152921505689281149 for App: 9NP77JJ47ZWT Flight: 46ed9740-4d9b-4258-9fba-3f4e096051aa]
2019-12-13 11:20:44 : cosminst : Successfully cloned the existing submission and modified its content.
You can view it on the Dev Portal here:
    https://dev.windows.com/en-us/dashboard/apps/9NP77JJ47ZWT/submissions/1152921505689281149/
or by running this command:
    Get-ApplicationFlightSubmission -AppId ... -FlightId ... -SubmissionId ... | Format-ApplicationFlightSubmission

PLEASE NOTE: Due to the nature of how the Store API works, you won't see any of your changes in the
Dev Portal until your submission has entered into certification.  It doesn't have to *complete*
certification for you to see your changes, but it does have to enter certification first.
If it's important for you to verify your changes in the Dev Portal prior to publishing,
consider publishing with the "Manual" targetPublishMode by setting that value in your
config file and then additionally specifying the -UpdatePublishModeAndVisibility switch
when calling Update-ApplicationFlightSubmission, or by specifying the
-TargetPublishMode Manual parameter when calling Update-ApplicationFlightSubmission.
DONE - Operation took 64 second(s) [Uploading C:\Users\cosminst\Documents\....appxupload]
2019-12-13 11:21:56 : cosminst : When you're ready to commit, run this command:
  Commit-ApplicationFlightSubmission -AppId ... -FlightId ... -SubmissionId ...
https://ingestionpackagesprod1.blob.core.windows.net/ingestion/bc99e295-e92c-4b2a-95b5-fec955472961?sv=2017-04-17&sr=b&sig=NP43c9B%2B80DQwctovWvGNV4p2A2o9S0R%2BjQAgc3%2B6nE%3D&se=2019-12-14T09:34:31Z&sp=rwl
```

**Comment by HowardWolosky** [comment]
There are some things wrong with your command.  You used your config file as your submissiondata, and you used your appxupload file as your package path.  `New-SubmissionPackage` generates a json and a zip file.  The json file is your `SubmissionDataPath` and the zip file is your `PackagePath`.

Given you provided an invalid json file as your `SubmissionData`, it failed to find the `NotesForCertification` which resulted in a null/empty string being used.

Also note: You would either need to add `-AutoCommit` to your `Update-Submission` command, or follow the final step in the eventual output similar to what you pasted in and call `Commit-ApplicationFlightSubmission` after `Update-ApplicationSubmission` in order for the submission to proceed with certification (`Commit-ApplicationFlightSubmission -AppId ... -FlightId ... -SubmissionId ...`).

My generally recommendation would be to run the following command:

```powershell
Update-ApplicationFlightSubmission -AppId ... -Flight ... -Force -SubmissionDataPath 'C:\Users\cosminst\Desktop\package.json' -PackagePath 'C:\Users\cosminst\Desktop\SBpackage.zip'  -UpdateNotesForCertification -TargetPublishMode Manual -AutoCommit
```
That will do everything in a single command (the `-Force` allows you to avoid calling `New-ApplicationSubmission` manually by automatically deleting the one that might already be there and then creating a new one).  By setting it to `Manual` `TargetPublishMode`, it will go through certification, but it won't actually publish our the update.  That way you can review the changes that it made in the Dev Portal to confirm it worked as expected (you can't view the results in the dev portal UNTIL it has hit certification, otherwise the mere act of looking at a submission in the dev portal that you submission via the v1 API will **undo** any changes you made via the API).  Then, if you're satisfied, just hit the publish button.  Once you're feeling confident with StoreBroker, you can switch to using `-TargetPublishMode Immediate`.

**Comment by cosminstirbu** [comment]
Indeed I have missed the `New-SubmissionPackage` step - as I have generated my `SubmissionDataPath` .json by manually editing the .json generated by `New-StoreBrokerConfigFile` and used the .appxupload as `PackagePath` instead of the .zip from `New-SubmissionPackage`.

However I have ended up using the following command:

`Update-ApplicationFlightSubmission -AppId ... -FlightId ... -SubmissionDataPath C:\Users\cosminst\Desktop\Test.json -PackagePath C:\Users\cosminst\Desktop\Test.zip -UpdateNotesForCertification -TargetPublishMode Manual -AutoCommit -SubmissionId ... -AddPackages` instead of using -Force, I have specified the SubmissionId because I was receiving an error - the -Force parameter deleted the existing submission which deleted the Flight.

Thank you for your help!

**Comment by HowardWolosky** [comment]
Glad you got that working.

> instead of using -Force, I have specified the SubmissionId because I was receiving an error - the -Force parameter deleted the existing submission which deleted the Flight.

Ah, that would happen if it was the _very first_ submission of a flight. You won't run into that problem in the future for that flight.
