### ISSUE TITLE
Unable to submit common screenshot for all languages

### ISSUE THREAD

**Issue by DaveMebs** [Microsoft/StoreBroker#28]
My package has localized listing data, but the screenshots have nothing to localize - they are language/region agnostic. I'd like to be able to submit a common screenshot to be used everywhere, rather than creating required the folder structure per language and duplicating the file N times.

**Comment by HowardWolosky** [comment]
@DaveMebs  - Sorry for not responding to this earlier.  I completely missed that this Issue was opened.  That's an interesting scenario.  So you're saying that even in your screenshot itself, there is no text or visual asset that would be localized/swapped out based on the user's language?

One way that I could see this being implemented would be to have a special "fallback" language folder during `Convert-ListingToObject` in `PackageTool.ps1`.  When it gets to `if ($null -eq $image)`, right now it errors out.  We could have one last check for that file in a special `common` folder (at the same level as the other languages) and it would look for the image there before failing.

That would be a fairly minimally invasive change and produce the result that you're looking for.  An additional change then to consider on top of that would be to copy it to a "common" language destination folder (as opposed to the language-specific sub-folder within the final StoreBroker payload) to reduce the size of the StoreBroker payload...otherwise the final payload will be larger than needed....we'd just have to check that the Submission API will allow shared screenshot files across languages (I'm not completely sure that it does).

**Comment by HowardWolosky** [comment]
Hmmm...another option is to let users just specify an actual language to fallback to, and it would look there.  So, users could specify `en-us` as the fallback language, and it would look for UK screenshot images in `en-GB` first, and if not found, would then try grabbing them from the `en-us` fallback folder before failing altogether.  I feel like this is a more natural way of doing this.  Wondering if you have any specific thoughts @DaveMebs

**Comment by DaveMebs** [comment]
In my specific case, I have a common image that is used across all languages with no localization ever used. Since the visual components of my package are not relevant to the user, I also only have this one image to upload.

In many ways, I like the idea of a fallback language over a fallback folder and agree with you that it seems more natural. At the same time, would someone ever have a screenshot localized in 50% of their target languages? That seems a bit odd and not a great user experience to design for.

The most likely case to me is that some images are localized and some are not. And the images that are not localized are never localized. It might make the most sense to have a "neutral" folder to support these and then consider enforcing that you cannot have an asset in both a lang folder and the neutral folder.

Thoughts?

**Comment by HowardWolosky** [comment]
This was resolved a while ago with #80
