### ISSUE TITLE
Start-SubmissionMonitor should allow the shell to know the result

### ISSUE THREAD

**Issue by taoyouh** [Microsoft/StoreBroker#43]
The Start-SubmissionMonitor should allow the shell to know the result by returning a status variable, which will be very useful in automated build servers.

**Comment by HowardWolosky** [comment]
@taoyouh - Thanks for the suggestion.  What specifically were you hoping the return value to be?  You're suggesting just the status variable...what if it returned the entire submission so that the status details (like errors/warnings/cert reports) could be examined by your automated build server as well?  Would that still fit your needs?

**Comment by taoyouh** [comment]
@HowardWolosky I was hoping for the last state the submission ends up into. First, I want to have a variable or something that enables me to know if the submission succeeded. Second, I think it will be better if I can know what the errors are.

**Comment by HowardWolosky** [comment]
@taoyouh - Thanks.  Returning the submission object as the result would achieve that, since you could grab the submission status from within it....it would be equivalent to calling Get-ApplicationSubmission afterwards to get the status, since that's what the monitor is doing internally to check on it.

**Comment by HowardWolosky** [comment]
@taoyouh - Please review [PR 45](https://github.com/Microsoft/StoreBroker/pull/45) and give that branch a try to see if it solves your issue.  To grab the final status, you'd do something like:

`$submission = Start-SubmissionMonitor ... 
 $finalStatus = $submission.status`

**Comment by HowardWolosky** [comment]
Fixed in 1.8.1.
