### ISSUE TITLE
Error with Update-ApplicationSubmission: Cannot convert argument "accessCondition", with value: "Open", for "UploadFromFile" to type "Microsoft.WindowsAzure.Storage.AccessCondition"

### ISSUE THREAD

**Issue by ADobin** [Microsoft/StoreBroker#49]
Version:  '1.8.1'
OS: 1703 (15063)
PowerShell Version: 5.1.15063

I've been using the tools for a couple of months now with no problems. I went to make a submission today and I keep seeing this error:

Write-Log : 2017-05-02 17:17:15 : adobin : Cannot convert argument "accessCondition", with value: "Open", for
"UploadFromFile" to type "Microsoft.WindowsAzure.Storage.AccessCondition": "Cannot convert value "Open" to type
"Microsoft.WindowsAzure.Storage.AccessCondition". Error: "Invalid cast from 'System.IO.FileMode' to
'Microsoft.WindowsAzure.Storage.AccessCondition'.""

It seems to be fixed if I run the command as an admin but I would prefer to not have to do that as it seemed to work before. Is this by design?

**Comment by HowardWolosky** [comment]
In [v1.8.0](https://github.com/Microsoft/StoreBroker/commit/0b260c47dd84ce6f85063acdfe8b3c4477793e66), we changed the version of the WindowsAzure.Storage assembly that we require.
StoreBroker loads the assembly into the context of the PowerShell session.  My guess is that the attempt to load the newer version over the older version is not working, and things aren't getting mapped correctly.

I'm guessing that you've been using the same PowerShell console window/session since before 1.8.0 and then sync'd after that.  The simplest solution should be to simply close your PowerShell window and open a new one and try again, as then it'll be in a fresh state.

If that doesn't work, then we'll likely need to dig into things a bit deeper.

**Comment by ADobin** [comment]
That does seem to fix the issue. Thanks for your help @HowardWolosky!
