### ISSUE TITLE
Confusing "Getting Your AppId" section in SETUP

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/StoreBroker#63]
Hi,
this should probably be changed - the [Getting Your AppID](https://github.com/Microsoft/StoreBroker/blob/master/Documentation/SETUP.md#getting-your-appid) section in SETUP.md is a bit confusing. It shows AppIn in format 0ABCDEF12345 but then it uses App Name in the command.
I found my **AppId in Dev Dashboard** and was wondering for few hours why the command is not working. The command should either use "id -like 0ABCDEF12345" or the difference between App name and Id should be described in a better way. Or just point the developer to the **App management -> App identity** section in **Dashboard** where the AppId is located.

Related issue that should probably be fixed as well - **more meaningful error messages** (should I create another ticket?).

If this command 
```
Get-Applications -GetAll | Where-Object primaryName -like "*<appName>*" | Format-Application
```
does not find any app, only this error message is displayed. I had to dig through the source code to discover that $ApplicationData in Format-Application is null and Write-Log then receives invalid Message parameter. This pointed me to wrong AppId in the command.

```
Write-Log : Cannot validate argument on parameter 'Message'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Users\marti\Documents\WindowsPowerShell\Modules\StoreBroker\StoreBroker\StoreIngestionApplicationApi.ps1:303 char:18
+        Write-Log $($output -join [Environment]::NewLine)
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Log], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Write-Log
```

**Comment by HowardWolosky** [comment]
Hi @martinsuchan -- thanks for the feedback.
Regarding your second issue first, you would have received your more meaningful help message if you hadn't piped the result directly into `Format-Application`.  The error you received was correct for `Format-Application`, as `Message` could have been invalid due to a myriad of reasons.  If you had _only_ run `Get-Applications -GetAll | Where-Object primaryName -like "*<appName>*"`, you would have seen that you had no results (which is the reason that `Format-Applications` was failing).  This is the nature of how PowerShell works with regards to piping command output from one command to another.  That is pretty much what that error is indicating as well (it's a standard PowerShell command validation error, given that it's PowerShell that is providing that error).  You could have then stepped back even further and just run `Get-Applications -GetAll` or `Get-Applications -GetAll | Format-Applications`.

For your first issue, I will update the documentation to also indicate that users can find the `AppId` in the dev portal.  StoreBroker was originally written for Microsoft prior to open-sourcing, and due to us enforcing security through least privilege, few employees actually have access to the dev portal itself.  Therefore, the common way for them to identify their app's `AppId` would be to search for their app's name in the full application list returned from StoreBroker, and then extract the `id` from the result.

**Comment by martinsuchan** [comment]
Regarding the error, I understand how piping commands work, but it might be more useful to throw "Format-Application -> ApplicationData is null" rather then trying to call Write-Log with null value.

**Comment by HowardWolosky** [comment]
Ah, I missed it was `Write-Log` throwing that parameter validation error.  Thanks.  In this case, I think I'll update `Write-Log` to accept null/empty string values for `Message`.  That would be more consistent with how PowerShell tends to deal with empty results sets (not throwing an error, just printing nothing).

I have separately updated the documentation both with your suggestion for alternatively grabbing it from the Dev Portal, as well as some clarification that users can also simply run `Get-Applications -GetAll | Format-Applications` if they don't have a ton of applications and they are having issues writing their query expression with `Where-Object`.
