### ISSUE TITLE
Convert relative OutPath to absolute path in Ensure-PdpFilePath

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/StoreBroker#64]
In **ConvertFrom-ExistingSubmission.ps1** if user enters **relative -OutPath** and launches the script from non-default folder, the OutPath folder is created in a wrong place and the **$xml.Save($filePath) throws an exception** because it can't find the target nested folder.
```
.\ConvertFrom-ExistingSubmission.ps1 -AppId "ABCDEFGH" -Release "Master" -PdpFileName "PDP.xml" -OutPath "PDPOut"
```
This creates the OutPath folder in Extensions directory, but $xml.Save($filePath) expects it in StoreBroker root directory.

Expected solution: Ensure-PdpFilePath should return absolute path where the OutPath folder was created.

**Comment by HowardWolosky** [comment]
Thanks for the report.
Looks like we should be using `Resolve-UnverifiedPath` here since it's calling out to a non-PowerShell command (`$xml.Save()`).  That command was introduced in [this commit](https://github.com/Microsoft/StoreBroker/commit/2a86150d134d3f0a1552b00b199dd252a6092a04) because package upload/download also use non-native command which means that they don't handle relative paths correctly.

@danbelcher-MSFT - Can you update those scripts to leverage `Resolve-UnverifiedPath`, and then make sure that there aren't any other code-paths in StoreBroker that take in a path to a non-native PowerShell method that haven't been resolved first?

Thanks.

**Comment by danbelcher-MSFT** [comment]
Closing this issue as resolved based on the linked commit.  Please let us know if you are still experiencing this issue.  Thanks!
